language: java
jdk: oraclejdk7
before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
# for gradle output style
- export TERM=dumb

# install android SDK
- wget http://dl.google.com/android/android-sdk_r22.6-linux.tgz
- tar -xzf android-sdk_r22.6-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
# manually set sdk.dir variable, according to local paths
- echo "sdk.dir=$ANDROID_HOME" > local.properties

# Install components
# "echo yes |" part is to accept license from android sdk manager tool
- echo yes | android update sdk -a -t tools --force --no-ui > /dev/null
- echo yes | android update sdk -a -t platform-tools --force --no-ui > /dev/null
- echo yes | android update sdk -a -t build-tools-19.0.1 --force --no-ui > /dev/null
- echo yes | android update sdk -a -t extra-android-support --force --no-ui > /dev/null
- echo yes | android update sdk -a -t extra-android-m2repository --force --no-ui > /dev/null
- echo yes | android update sdk -a -t android-16 --force --no-ui > /dev/null
- echo yes | android update sdk -a -t sysimg-16 --force --no-ui > /dev/null

# Create and start emulator
- echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &

before_script:
- adb wait-for-device
- adb shell input keyevent 82 &

script:
- ./gradlew check
- ./gradlew connectedInstrumentTest
